/**
 * Embed script: reads web/dist/index.html and generates src/web_content.h
 * Usage: node scripts/embed.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const htmlPath = join(root, 'web', 'dist', 'index.html')
const outPath = join(root, 'src', 'web_content.h')

let html
try {
  html = readFileSync(htmlPath, 'utf-8')
} catch (e) {
  console.error('Error: web/dist/index.html not found. Run "npm run build" in web/ first.')
  process.exit(1)
}

// Escape the sequence ")HTML" so it doesn't prematurely close the raw string
const safe = html.replace(/\)HTML/g, ')HTML\\')

// MSVC limits a single string literal to 16380 bytes (C2026).
// Split the content into byte-sized chunks under that limit. C++ concatenates
// adjacent string literals automatically: R"HTML(a)HTML" R"HTML(b)HTML" == "ab".
// We chunk by bytes (not chars) because multi-byte UTF-8 can make 16000 chars
// exceed 16380 bytes.
const CHUNK_BYTES = 15000
const buf = Buffer.from(safe, 'utf-8')
const chunks = []
let pos = 0
while (pos < buf.length) {
  let end = Math.min(pos + CHUNK_BYTES, buf.length)
  if (end < buf.length) {
    // Walk back to avoid splitting a multi-byte UTF-8 continuation byte
    while (end > pos && (buf[end] & 0xC0) === 0x80) end--
  }
  chunks.push(buf.slice(pos, end).toString('utf-8'))
  pos = end
}

const parts = chunks.map(c => `R"HTML(${c})HTML"`).join('\n  ')

const header = `#ifndef CHROME_GREEN_SRC_WEB_CONTENT_H_
#define CHROME_GREEN_SRC_WEB_CONTENT_H_

// Auto-generated by scripts/embed.mjs — DO NOT EDIT
// Source: web/dist/index.html (${new Date().toISOString()})
// Split into ${chunks.length} raw-string chunks to stay under MSVC's 16380-byte limit.

#include <string>

inline const char* GetWebContent() {
  return ${parts};
}

#endif  // CHROME_GREEN_SRC_WEB_CONTENT_H_
`

writeFileSync(outPath, header, 'utf-8')
console.log(`Generated ${outPath} (${Buffer.byteLength(html, 'utf-8')} bytes HTML)`)
